### ISSUE TITLE
Allow for accessing an application's app icon

### ISSUE THREAD

**Issue by GroovinChip** [g123k/flutter_plugin_device_apps#1]

**Comment by GroovinChip** [comment]
any interest in implementing this?

**Comment by lohanidamodar** [comment]
@GroovinChip  Hi, I just added app icon field, that returns icon as base64 encoded string and updated the example to show the app icon. I have created a pull request too...if you want you can use it from my fork of the repo at
https://github.com/lohanidamodar/flutter_plugin_device_apps
