### ISSUE TITLE
Adapt with Flutter 1.6

### ISSUE THREAD

**Issue by DreamBuddy** [g123k/flutter_plugin_device_apps#11]
W/Binder  ( 8963): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 8963): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread.

similar link : https://github.com/flutter/flutter/issues/32315

**Comment by DreamBuddy** [comment]
Use this and wrap the origin result can solve the problem ~
// MethodChannel.Result wrapper that responds on the platform thread.
    private static class MethodResultWrapper implements MethodChannel.Result {
        private MethodChannel.Result methodResult;
        private Handler handler;

        MethodResultWrapper(MethodChannel.Result result) {
            methodResult = result;
            handler = new Handler(Looper.getMainLooper());
        }

        @Override
        public void success(final Object result) {
            handler.post(new Runnable() {
                @Override
                public void run() {
                    methodResult.success(result);
                }
            });
        }

        @Override
        public void error(final String errorCode, final String errorMessage, final Object errorDetails) {
            handler.post(new Runnable() {
                @Override
                public void run() {
                    methodResult.error(errorCode, errorMessage, errorDetails);
                }
            });
        }

        @Override
        public void notImplemented() {
            handler.post(new Runnable() {
                @Override
                public void run() {
                    methodResult.notImplemented();
                }
            });
        }
    }

**Comment by g123k** [comment]
Fixed in 1.0.8
