### ISSUE TITLE
Missing Plugin Exception on iOS

### ISSUE THREAD

**Issue by Skullper** [g123k/flutter_plugin_device_apps#14]
Hi!
Got an exception on iOS when trying to get all installed apps in the simulator:

`
flutter: MissingPluginException(No implementation found for method getInstalledApps on channel g123k/device_apps)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'FutureOr<List<Application>>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:144:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#3      Future._completeError (dart:async/future_impl.dart:491:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
#7      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
<asynchronous suspension>
#8      DeviceApps.getInstalledApplications (package:device_apps/device_apps.dart:14:21)
<asynchronous suspension>
#9      _MyHomePageState._launchSignNow (package:another_app_opener/main.dart:63:47)
<asynchronous suspension>
#10     _InkRespons<…>
`

Code which should get app names:

`
_launchSignNow() async {
    List<Application> apps = await DeviceApps.getInstalledApplications(
        onlyAppsWithLaunchIntent: true, includeSystemApps: true);
    for (var app in apps) {
      print(app.appName);
    }
  }
`

How can I fix this?

**Comment by Skullper** [comment]
Sorry miss that library doesn't support iOS

**Comment by KLD** [comment]
Apparently I missed that too
