### ISSUE TITLE
Add a property to the Application class that differentiates user and system apps

### ISSUE THREAD

**Issue by GroovinChip** [g123k/flutter_plugin_device_apps#2]
As such, we can treat them differently, a la Titanium Backup

**Comment by g123k** [comment]
Hello,

Thanks for your feature request.
You have now a `systemApp` attribute in the `Application` object to detect what kind of app it is.

Just upgrade to the 1.0.1 version to enjoy it :)

**Comment by GroovinChip** [comment]
Thanks!
