### ISSUE TITLE
[Feature Request] Permission managment

### ISSUE THREAD

**Issue by philippklemmer** [g123k/flutter_plugin_device_apps#32]
Hey there,

thanks for your nice plugin. Would it be possible to add a feature like seeing permissions of those apps? I would also try to it via PR but never did Android development. This might take a while :D

Stay healthy!

**Comment by g123k** [comment]
I am not sure of the idea behind this use case.
Why would you need the permissions requested by other apps?

**Comment by g123k** [comment]
Without any response, I close the ticket
