### ISSUE TITLE
DeviceAppsPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Kalyanb447-github** [g123k/flutter_plugin_device_apps#33]
Note: C:\Users\kalya\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides a deprecated API.

**Comment by g123k** [comment]
Yes this a warning, not an error.

**Comment by Rosco89** [comment]
!!!NOW!! it's a warning.

**Comment by g123k** [comment]
Not a bug, closing this
