### ISSUE TITLE
Is device_apps plugin deprecated? 

### ISSUE THREAD

**Issue by Sankalpjadhav** [g123k/flutter_plugin_device_apps#42]
When I try to use it my project, it is showing this plugin is deprecated. So is there any alternate method?

**Comment by g123k** [comment]
No the plug-in is still supported
Don't worry about the warnings

Le ven. 3 juil. 2020 à 04:19, Sankalp jadhav <notifications@github.com> a
écrit :

**Comment by Sankalpjadhav** [comment]
Thank you for the response!
