### ISSUE TITLE
Apps by category

### ISSUE THREAD

**Issue by holy-dev** [g123k/flutter_plugin_device_apps#56]
I want to get list of apps of a specific category, is it possible?

**Comment by g123k** [comment]
Yes, you just have to filter the list:

```dart
List<Application> list = await DeviceApps.getInstalledApplications();
list.where((Application app) => app.category == ApplicationCategory.video);
```

**Comment by yashwp** [comment]
@g123k I cannot find Finance category, can you please tell, is it possible to fetch that?

**Comment by g123k** [comment]
@yashwp No, the categories are provided by Android

**Comment by kashi1996** [comment]
after this line
list.where((Application app) => app.category == ApplicationCategory.video);

the data be like 

(Application{appName: Tic Tac Toe, apkFilePath: /data/app/~~ScMRDLOHYNRAv6IXFZCnUQ==/com.anmolsethi.tictactoe-XdTuB6HbZg2wWXNvn2watA==/base.apk, packageName: com.anmolsethi.tictactoe, versionName: 2.0.2mp, versionCode: 10, dataDir: /data/user/0/com.anmolsethi.tictactoe, systemApp: false, installTimeMillis: 1655580516006, updateTimeMillis: 1655580516006, category: ApplicationCategory.game, enabled: true})

which seems inaccessible how can we handle this small brackets("(") and how can we access data from the object 

e.g:  i like to access appName from this object
