### ISSUE TITLE
Android Deprecated API

### ISSUE THREAD

**Issue by NaingMyoThawNMYT** [g123k/flutter_plugin_device_apps#57]
**Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-1.2.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides a deprecated API.**

Please can you fix it?
Thank you!

**Comment by g123k** [comment]
This is just a warning, not an issue.
