### ISSUE TITLE
Some assertions fail while testing on device

### ISSUE THREAD

**Issue by aswinmohanme** [g123k/flutter_plugin_device_apps#6]
The new version 1.0.3 has added some assertions. The assertion 'version_code" is throwing an error while testing on my device. I downgraded  to 1.0.2 which does not have that issue.

**Comment by g123k** [comment]
Hi @aswinmohanme,

Could you give an example of the app without the version code ?

**Comment by aswinmohanme** [comment]
It was an issue with my code, fixed it :relaxed:
