### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'Future<bool>' in type cast

### ISSUE THREAD

**Issue by iptodays** [g123k/flutter_plugin_device_apps#67]
`DeviceApps.isAppInstalled(packageName)`
![image](https://user-images.githubusercontent.com/15830996/112160917-9831a100-8c25-11eb-8dde-582824bf8929.png)
![image](https://user-images.githubusercontent.com/15830996/112161075-bdbeaa80-8c25-11eb-9746-ea39bbd5c099.png)

**Comment by g123k** [comment]
Thanks for the report.
I'm currently working on a fix

**Comment by g123k** [comment]
Fixed in 2.0.1 :)
