### ISSUE TITLE
can't get dual app

### ISSUE THREAD

**Issue by shinewanna** [g123k/flutter_plugin_device_apps#68]
I'm using dual app.When get all apps, only the real app found in retrieve get all app list, not including clone app.

**Comment by g123k** [comment]
Please be more specific. What is a dual app?

Le dim. 28 mars 2021 à 12:49, Shine Wanna ***@***.***> a
écrit :

**Comment by shinewanna** [comment]
dual app is cloning app, like if u want to use two twitter account parallel, u can create the twitter clone in setting.
Search 'dual' in your setting, it may be found.
I think only new model device have that feature, but if don't have u can download dual app from play store to clone your app.
I hope u'll understand, otherwise search 'Enable Dual Apps in MIUI' in google, u'll get it.

**Comment by g123k** [comment]
This is not an official feature from the Android SDK (MIUI thing as you
mentionned)
As I dont have a Xiaomi phone, I can't do anything.

Le dim. 28 mars 2021 à 14:02, Shine Wanna ***@***.***> a
écrit :
