### ISSUE TITLE
Application event listener not being called

### ISSUE THREAD

**Issue by danbrun** [g123k/flutter_plugin_device_apps#69]
I noticed that in version 2.0.1, my application event listener isn't getting called.

The issue seems to be the cast to `Map<Object, Object>` in [the broadcast map lambda](https://github.com/g123k/flutter_plugin_device_apps/blob/master/lib/src/plugin.dart#L148).
I discovered this by logging the error in [the error handler](https://github.com/g123k/flutter_plugin_device_apps/blob/master/lib/src/plugin.dart#L150), which resulted in this message:
`type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<Object, Object>' in type cast`

Casting to `Map<dynamic, dynamic>` instead or removing the cast altogether fixed the problem.

**Comment by g123k** [comment]
Thanks for the report.
Which method of the lib are you using please?

**Comment by danbrun** [comment]
I'm using `DeviceApps.listenToAppsChanges().listen((event) {...})` to update a list of apps.

**Comment by danbrun** [comment]
It looks like `DeviceApps.getApp` has a similar issue, [the type check](https://github.com/g123k/flutter_plugin_device_apps/blob/master/lib/src/plugin.dart#L82) fails resulting in a null return. Changing `Map<Object, Object>` to `Map<dynamic, dynamic>` fixes the issue.

**Comment by g123k** [comment]
Should be fixed in 2.0.2.
Thanks for your report
