### ISSUE TITLE
How and when will 2.1.0 be released?

### ISSUE THREAD

**Issue by mbalmer** [g123k/flutter_plugin_device_apps#73]
Is it correct that this repository is a copy of some internal repo?  As it has no releases and no tags, I wonder how and when 2.1.0 will be release to pub.dev?

**Comment by g123k** [comment]
Ooops sorry I totally forgot to publish it -> DONE

**Comment by mbalmer** [comment]
> 
> Ooops sorry I totally forgot to publish it -> DONE
> 
> 
Cool, thanks!
