### ISSUE TITLE
Build Failed Issue (device_apps: ^2.1.0 and flutter: 2.0.5)

### ISSUE THREAD

**Issue by NaingMyoThawNMYT** [g123k/flutter_plugin_device_apps#74]
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:18: error: c
annot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\listener\DeviceAppsChangedListener
.java:8: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:65: error: c
annot find symbol
    public void onAttachedToEngine(@NonNull FlutterPluginBinding binding) {
                                    ^
  symbol:   class NonNull
  location: class DeviceAppsPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:80: error: c
annot find symbol
    public void onMethodCall(MethodCall call, @NonNull final Result result) {
                                               ^
  symbol:   class NonNull
  location: class DeviceAppsPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:179: error:
cannot find symbol
    private boolean openApp(@NonNull String packageName) {
                             ^
  symbol:   class NonNull
  location: class DeviceAppsPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:195: error:
cannot find symbol
    private boolean openAppSettings(@NonNull String packageName) {
                                     ^
  symbol:   class NonNull
  location: class DeviceAppsPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:217: error:
cannot find symbol
    private boolean isAppInstalled(@NonNull String packageName) {
                                    ^
  symbol:   class NonNull
  location: class DeviceAppsPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java:335: error:
cannot find symbol
    public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
                                      ^
  symbol:   class NonNull
  location: class DeviceAppsPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\listener\DeviceAppsChangedListener
.java:27: error: cannot find symbol
    public void register(@NonNull Context context, EventChannel.EventSink events) {
                          ^
  symbol:   class NonNull
  location: class DeviceAppsChangedListener
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\listener\DeviceAppsChangedListener
.java:101: error: cannot find symbol
    public void unregister(@NonNull Context context) {
                            ^
  symbol:   class NonNull
  location: class DeviceAppsChangedListener
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-2.1.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses o
r overrides a deprecated API.

**Comment by leonardoayres** [comment]
Same issue here.

Got to find another plugin :-/

**Comment by g123k** [comment]
Working perfectly well with Flutter 2.10
