### ISSUE TITLE
Shows Application with package name "com.google.android.youtube" is not installed on this device 

### ISSUE THREAD

**Issue by sahalkabeer** [g123k/flutter_plugin_device_apps#83]
I tried it on emulator also on physical device

**Comment by g123k** [comment]
@sahalkabeer Could you detail which method you call, please?

**Comment by albatrosify** [comment]
I do have the same problem. DeviceApps.openApp('...') always shows this App is not installed.
It works however when you add Query_All_Packages permission.
Without that permission I am unable to open another app from now on.
