### ISSUE TITLE
Plugin doesn't work on Android 12

### ISSUE THREAD

**Issue by Djihanegh** [g123k/flutter_plugin_device_apps#94]
Plugin doesn't work on android 12, but it works on android 10

Flutter version : **3.0.5**
Dart **2.17.6**
device_apps: **^2.2.0**

Is there any solution for that ?
Thank you in advance.

**Comment by kayumarie** [comment]
I'm getting an error
```
Error: Couldn't resolve the package 'device_apps' in 'package:device_apps/device_apps.dart'.
```

@Djihanegh are you getting the same one?

**Comment by Djihanegh** [comment]
No, i was having a problem with Android 12, to check if some applications are installed or not, and i fixed it by adding
 ` <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />` in AndroidManifest.xml..
![image](https://user-images.githubusercontent.com/40029149/194875157-9b38daec-c64d-497d-b480-232de1e8c068.png)

check more details here :  [https://pub.dev/packages/device_apps](url)
